Created Food Website Template
arpit456jain/Cool-Front-End_Templates pull request #103
Opened 2021-07-24 17:06 UTC by sidparashar2001

# Description

Created a completely responsive and attractive food website template

Fixes #101

2021-07-24 17:13 UTC, sidparashar2001 commented
![image](https://user-images.githubusercontent.com/74417028/126876135-d47bd540-005c-47c0-811e-6aba0526c86a.png)

2021-07-24 17:28 UTC, arpit456jain commented
@sidparashar2001 Is this from YouTube
Code with Harry ??

2021-07-24 17:33 UTC, arpit456jain commented
@sidparashar2001 Is this from YouTube
Code with Harry ??

2021-07-24 17:34 UTC, sidparashar2001 commented
Yes I took the reference but can check the code and some styling it's bit different

2021-07-24 17:35 UTC, arpit456jain commented
Yeah @sidparashar2001 no problem actually same two templates are already present but no worries every contribution counts

2021-07-24 17:37 UTC, sidparashar2001 commented
Thanks😊

2021-07-24 17:37 UTC, arpit456jain commented
https://deploy-preview-103--cool-front-end-templates.netlify.app/food%20website%20template/

I think there is some problem can you please confirm @ankitapuri

2021-07-24 17:40 UTC, arpit456jain requested changes

2021-07-24 17:40 UTC, arpit456jain commented on Food Website Template/index.html
> +    <link rel="stylesheet" media="screen and (max-width:900px)" href="/css/phone.css">
Just use css/style.css 
Do not use / before it i think because of this it is finding css in root directory

2021-07-24 19:47 UTC, ankitapuri commented
> https://deploy-preview-103--cool-front-end-templates.netlify.app/food%20website%20template/
> 
> I think there is some problem can you please confirm @ankitapuri

yes its only plain html

2021-07-25 03:36 UTC, arpit456jain commented
@sidparashar2001 please make required changes asap

2021-07-25 04:40 UTC, sidparashar2001 commented
Updated the changes Sorry for the mistake

2021-07-25 04:44 UTC, sidparashar2001 commented
Sorry for the Mistake Updated the changes

2021-07-25 04:47 UTC, merged